// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCx3nx3yOP-eL78HtRpn3m8f2HCk_y2HmE',
    appId: '1:957738434377:web:0543bbf7c1eda80df42498',
    messagingSenderId: '957738434377',
    projectId: 'image-app-f7aa8',
    authDomain: 'image-app-f7aa8.firebaseapp.com',
    storageBucket: 'image-app-f7aa8.appspot.com',
    measurementId: 'G-N3EG7BR3V8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxYR3l3n4d5hnYP0ye7NaCz6gDoAq9CBM',
    appId: '1:957738434377:android:a1057763eca48b21f42498',
    messagingSenderId: '957738434377',
    projectId: 'image-app-f7aa8',
    storageBucket: 'image-app-f7aa8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtEP2jq24KlLHHu1QZ0w7ra5QP-yfU6uQ',
    appId: '1:957738434377:ios:845220a44bd394eff42498',
    messagingSenderId: '957738434377',
    projectId: 'image-app-f7aa8',
    storageBucket: 'image-app-f7aa8.appspot.com',
    iosBundleId: 'com.example.imageApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtEP2jq24KlLHHu1QZ0w7ra5QP-yfU6uQ',
    appId: '1:957738434377:ios:845220a44bd394eff42498',
    messagingSenderId: '957738434377',
    projectId: 'image-app-f7aa8',
    storageBucket: 'image-app-f7aa8.appspot.com',
    iosBundleId: 'com.example.imageApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCx3nx3yOP-eL78HtRpn3m8f2HCk_y2HmE',
    appId: '1:957738434377:web:85413a395317571df42498',
    messagingSenderId: '957738434377',
    projectId: 'image-app-f7aa8',
    authDomain: 'image-app-f7aa8.firebaseapp.com',
    storageBucket: 'image-app-f7aa8.appspot.com',
    measurementId: 'G-6X53ZDZVVS',
  );
}
