version: '3.8'

services:
  login:
    build:
      context: ./app_login_log
    ports:
      - "8000:8001"

  images:
    build:
      context: ./app_envio_imagens
    ports:
      - "8000:8002"

  gateway:
    build: ./nginx
    ports:
      - "8000:80"